services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: true

    PrestaShop\Module\TailoredProductsPricing\Adapter\ColorAttributeProvider:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    PrestaShop\Module\TailoredProductsPricing\Service\DimensionsFieldsProvider: ~
        # autowires ProductConfigRepository by type

    PrestaShop\Module\TailoredProductsPricing\Service\AddToCartCustomizer: ~
        # autowires ProductConfigRepository by type

    PrestaShop\Module\TailoredProductsPricing\Service\ProductChoicesProvider: ~
        # autowires ProductConfigRepository by type

    PrestaShop\Module\TailoredProductsPricing\Repository\ProductConfigRepository:
        class: PrestaShop\Module\TailoredProductsPricing\Repository\ProductConfigRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - PrestaShop\Module\TailoredProductsPricing\Entity\TppProductConfig

    PrestaShop\Module\TailoredProductsPricing\Repository\CombinationConfigRepository:
        class: PrestaShop\Module\TailoredProductsPricing\Repository\CombinationConfigRepository
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - PrestaShop\Module\TailoredProductsPricing\Entity\TppCombinationConfig

    PrestaShop\Module\TailoredProductsPricing\Service\PriceWriter:
        arguments:
            $connection: '@doctrine.dbal.default_connection'

    PrestaShop\Module\TailoredProductsPricing\Service\PriceCalculator: ~
