services:
    PrestaShop\Module\TailoredProductsPricing\Form\Modifier\ProductFormModifier:
        autowire: true
        public: true
        arguments:
            $formBuilderModifier: '@form.form_builder_modifier'

    PrestaShop\Module\TailoredProductsPricing\Adapter\CombinationConfigRepository:
        autowire: true
        public: true

    PrestaShop\Module\TailoredProductsPricing\Form\Modifier\CombinationFormModifier:
        autowire: true
        public: true
